name: Publish - Nuget

on:
  push:
    branches:
      - main

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./src
        
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ./src/SqModel/SqModel.csproj
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
